### ISSUE TITLE
bspwm directory

### ISSUE THREAD

**Issue by Nota30** [Miusaky/dotfiles#1]
Isn't there supposed to be bspwm directory in the config?

**Comment by Miusaky** [comment]
No. The bspwm config needs to be cloned from a tag. See the [wiki](https://github.com/Miusaky/dotfiles/wiki/bspwm) for more details. In short:

```
git clone -b bspwm-1.0 https://github.com/Miusaky/bspdots $HOME/dotfiles
```

If you do not wish to use Git it can also be downloaded [here](https://github.com/Miusaky/dotfiles/archive/refs/tags/bspwm-1.0.zip)
