### ISSUE TITLE
Issue with making the config

### ISSUE THREAD

**Issue by chqir** [Miusaky/dotfiles#2]
I'm a relatively new Arch user, but have used linux for a while. After following the steps for dwm in the wiki, it appears that there is no makefile in the $HOME/.config/dwm/dwm directory. 

I am receiving an error:
`make: *** No rule to make target 'install'. Stop.`

Is there anything I should be doing differently?

**Comment by Miusaky** [comment]
I assume you solved this on your own but for others who run into the same problem make sure you're in the correct folder e.g. ```.config/dwm/dwm```.
