### ISSUE TITLE
API Key in BSPWM config

### ISSUE THREAD

**Issue by wxifuwu** [Miusaky/dotfiles#3]
Hey there!

I just wanted to let you know that _most likely_ your OpenWeatherMap API Key is included in the bspwm config, in case it isn't intended to be like that.

The file would be .config/polybar/scripts/key.txt

**Comment by Miusaky** [comment]
Hi! I'm aware it is there. I don't use it and it is not tied to me - so I have left it in. Worst case scenario it is revoked and stops working, in which case the people who still use it will have to replace it with their own.

Thank you for the concern none the less!
